name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: '3.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Set up environment
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        cp .env.example .env
        echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env

    - name: Set up database
      run: |
        task db:up
        sleep 5  # Give DB time to initialize
        task db:recreate

    - name: Run install and lint
      run: task ci

    - name: Run test coverage
      run: task test:coverage

    - name: Clean up database
      if: always()
      run: task db:down